### ISSUE TITLE
MPRIS won't install

### ISSUE THREAD

**Issue by SuperPichu** [twolfson/google-music-electron#37]
I get this 

```
npm ERR! Linux 4.4.1-2-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--ignore-scripts" "--save" "false" "electron-rebuild@~1.0.2" "mpris-service@~1.0.1"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.1

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/google-music-electron/npm-debug.log

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Expected "npm install" exit code to be "0" but it was "1"
    at ChildProcess.handleExit (/usr/lib/node_modules/google-music-electron/lib/install-mpris.js:33:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

when I run `sudo google-music -electron install-mpris` after installing with `sudo npm install -g google-music-electron` 

[npm-debug.txt](https://github.com/twolfson/google-music-electron/files/119972/npm-debug.txt)

**Comment by twolfson** [comment]
This sounds like an error inside of `npm`:

```
3721 verbose stack TypeError: Cannot read property 'target' of null
3721 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/filter-invalid-actions.js:24:35)
3721 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
3721 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
3721 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
3721 verbose stack     at Object.Installer.computeLinked (/usr/lib/node_modules/npm/lib/install.js:411:41)
3721 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
3721 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
3721 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
3721 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/diff-trees.js:50:3)
3721 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
```

I suggest downgrading to `npm@2.x.x` and trying it again:

``` bash
npm install -g npm@latest-2
```

**Comment by SuperPichu** [comment]
That worked. Thanks! You may just want to add that to the readme, since its an issue with the newer versions of npm

**Comment by twolfson** [comment]
I am hoping that they patch it sooner rather than later since the issue is definitely not strictly tied to our repo =(

This was also reported here: https://github.com/twolfson/google-music-electron/issues/25#issuecomment-167365140
